#!/bin/bash
# deng-toolkit setup script
# Installs as a Claude Code plugin

set -e

TOOLKIT_DIR="$HOME/.deng-toolkit"

echo "=========================================="
echo "  deng-toolkit plugin installer"
echo "=========================================="
echo ""

# Verify we're in the right place
if [ ! -f "$TOOLKIT_DIR/.claude-plugin/plugin.json" ]; then
    echo "ERROR: plugin.json not found at $TOOLKIT_DIR/.claude-plugin/"
    echo "Make sure you've cloned the repo to ~/.deng-toolkit/"
    exit 1
fi

# Check if claude CLI is available
if ! command -v claude &> /dev/null; then
    echo "ERROR: claude CLI not found in PATH"
    echo "Install Claude Code first: https://docs.anthropic.com/en/docs/claude-code"
    exit 1
fi

echo "Installing deng-toolkit plugin..."
echo ""

# Add the plugin globally (user scope)
claude plugins add "$TOOLKIT_DIR" --scope user 2>/dev/null || {
    echo "Note: Plugin may already be installed or claude plugins command syntax differs."
    echo "To manually install, add this to your Claude Code settings:"
    echo ""
    echo '  "plugins": ['
    echo "    \"$TOOLKIT_DIR\""
    echo '  ]'
    echo ""
}

# ==========================================
# Configure Data Catalog
# ==========================================
echo ""
echo "Configure data catalog location:"
echo "(The catalog stores metadata about your databases)"
echo ""

# Check for existing config
CONFIG_FILE="$TOOLKIT_DIR/config.yaml"
EXISTING_CATALOG_DIR=""
EXISTING_CATALOG_REMOTE=""

if [ -f "$CONFIG_FILE" ]; then
    EXISTING_CATALOG_DIR=$(grep "^catalog_dir:" "$CONFIG_FILE" 2>/dev/null | sed 's/catalog_dir: *//' | sed "s|~|$HOME|" | tr -d '"' | tr -d "'")
    EXISTING_CATALOG_REMOTE=$(grep "^catalog_remote:" "$CONFIG_FILE" 2>/dev/null | sed 's/catalog_remote: *//' | tr -d '"' | tr -d "'")
fi

# Prompt for catalog directory
DEFAULT_CATALOG_DIR="${EXISTING_CATALOG_DIR:-$HOME/data-catalog}"
read -p "Catalog directory [$DEFAULT_CATALOG_DIR]: " CATALOG_DIR
CATALOG_DIR="${CATALOG_DIR:-$DEFAULT_CATALOG_DIR}"

# Expand ~ in path
CATALOG_DIR="${CATALOG_DIR/#\~/$HOME}"

# Prompt for catalog remote
echo ""
echo "For team collaboration, enter the git remote URL for the catalog."
echo "(Leave blank for local-only setup)"
read -p "Catalog git remote URL [${EXISTING_CATALOG_REMOTE:-none}]: " CATALOG_REMOTE
CATALOG_REMOTE="${CATALOG_REMOTE:-$EXISTING_CATALOG_REMOTE}"

# Write config.yaml
echo ""
echo "Writing configuration to $CONFIG_FILE..."
cat > "$CONFIG_FILE" << EOF
# deng-toolkit configuration
# Generated by setup.sh on $(date +"%Y-%m-%d")

# Where the data catalog lives (can be a git repo for team collaboration)
catalog_dir: $CATALOG_DIR

# Git remote URL for catalog (leave empty for local-only)
catalog_remote: $CATALOG_REMOTE
EOF

echo "  catalog_dir: $CATALOG_DIR"
echo "  catalog_remote: ${CATALOG_REMOTE:-<none>}"

# ==========================================
# Initialize or Clone Catalog
# ==========================================
echo ""

if [ -n "$CATALOG_REMOTE" ] && [ ! -d "$CATALOG_DIR" ]; then
    echo "Cloning catalog from $CATALOG_REMOTE..."
    git clone "$CATALOG_REMOTE" "$CATALOG_DIR" || {
        echo "WARNING: Failed to clone from $CATALOG_REMOTE"
        echo "Creating empty catalog directory instead..."
        mkdir -p "$CATALOG_DIR"
    }
elif [ ! -d "$CATALOG_DIR" ]; then
    echo "Creating catalog directory at $CATALOG_DIR..."
    mkdir -p "$CATALOG_DIR"
fi

# Initialize git if not already a repo
if [ ! -d "$CATALOG_DIR/.git" ]; then
    echo "Initializing git repository in $CATALOG_DIR..."
    cd "$CATALOG_DIR"
    git init -q

    # Create .gitignore for credentials
    cat > .gitignore << 'EOF'
# Credentials and connection info
.env
targets.toml

# Temporary files
*.tmp
*.bak

# OS files
.DS_Store
Thumbs.db
EOF

    echo "Created .gitignore (excludes credentials)"

    # Set up remote if provided
    if [ -n "$CATALOG_REMOTE" ]; then
        echo "Adding git remote: $CATALOG_REMOTE"
        git remote add origin "$CATALOG_REMOTE" 2>/dev/null || true
    fi
fi

echo ""
echo "=========================================="
echo "  Installation complete!"
echo "=========================================="
echo ""
echo "Available commands:"
echo "  /deng-catalog-refresh    - Rebuild database metadata catalog"
echo "  /deng-find-data          - Search catalog for tables/columns"
echo "  /deng-build-ontology     - Build JSON-LD knowledge graph"
echo "  /deng-analyze-procedures - Extract SQL patterns from stored procs"
echo "  /deng-catalog-status     - Check catalog freshness"
echo "  /deng-catalog-sync       - Sync catalog with team repository"
echo ""
echo "MCP Tools (available as tools):"
echo "  search_catalog           - Search by keywords"
echo "  get_table_details        - Get table/column details"
echo "  find_join_paths          - Find FK relationships"
echo "  get_catalog_status       - Check catalog status"
echo ""
echo "Configuration:"
echo "  Config file: $CONFIG_FILE"
echo "  Catalog: $CATALOG_DIR"
if [ -n "$CATALOG_REMOTE" ]; then
    echo "  Remote: $CATALOG_REMOTE"
fi
echo ""
echo "Team collaboration:"
echo "  /deng-catalog-sync --pull   - Pull latest from team"
echo "  /deng-catalog-sync --full   - Pull, sync OneDrive, commit, push"
echo "  /deng-catalog-sync --status - Show configuration"
echo ""
echo "To uninstall:"
echo "  claude plugins remove deng-toolkit"
echo ""
